### ISSUE TITLE
Welding countries into groups/regions & zooming in to reveal countries

### ISSUE THREAD

**Issue by MarcusJT** [manifestinteractive/jqvmap#1]
It's a fairly common requirement for corporate web sites that there is a map showing global corporate presence, usually first shown by region of the world, then by country within each region.

It would be great if jqvmap offered a way to do this by dynamically welding countries together into regions (by providing a mapping between region names and lists of countries within each region) and then when the region is clicked to smoothly zoom in to fill the render area with the region, and thereby also reveal the individual countries within the region.

**Comment by wiesson** [comment]
Any updates to this feature?

**Comment by wiesson** [comment]
:(

**Comment by manifestinteractive** [comment]
It's just not possible with this project and I'd have no idea how to implement it. Was hoping to see someone contribute to this, like the other older tickets, but people are complaining about the number of unresolved tickets, so I had to clean house :(

**Comment by wiesson** [comment]
Ok, thanks for the response. If I can solve it, I will do a pull request some day.
