### ISSUE TITLE
Can't swipe/scroll on mobile devices

### ISSUE THREAD

**Issue by stompweb** [manifestinteractive/jqvmap#101]
Jvector map seems to be fine with this but jqvmap doesn't allow scrolling which, when zoomed in on say the iPad makes it's unusable.

Any ideas how to fix this?

**Comment by manifestinteractive** [comment]
This is an interesting feature as I think this will be important if JQVMap intends to work 100% on mobile devices.  I will work on this for a new release.

**Comment by manifestinteractive** [comment]
This is now integrated into https://github.com/manifestinteractive/jqvmap/tree/issue-101 and ready for testing.  This branch supports mobile touch, pinch & zoom.  A new example mobile.html map has also been added to demo some suggested features for mobile based maps.

**Comment by manifestinteractive** [comment]
There is now a PR for this at #186

**Comment by aswzen** [comment]
How to disable this feature? because i just **enableZoom: false**, but mobile device still able to pinch zoom using two finger
