### ISSUE TITLE
Dynamically update values without redrawing map

### ISSUE THREAD

**Issue by Tarang** [manifestinteractive/jqvmap#104]
How can one dynamically update values

i.e if i do

```
jQuery('#vmap').html('').vectorMap({
      map: 'world_en',
      backgroundColor: null,
      color: '#ffffff',
      hoverOpacity: 0.7,
      selectedColor: '#666666',
      enableZoom: true,
      showTooltip: true,
      values: data,
      scaleColors: ['#C8EEFF', '#006491'],
      normalizeFunction: 'polynomial'
    }); 
```

Then to change the value of one of the countries e.g `{'de':4}` is this possible without having to redraw the whole map?

**Comment by manifestinteractive** [comment]
That method will not work.  You will need to destroy the jQuery object using the standard way of destroying jQuery objects.
