### ISSUE TITLE
Washington DC is missing on USA Map

### ISSUE THREAD

**Issue by esiteq** [manifestinteractive/jqvmap#106]
Could you fix this issue?

**Comment by davesbrown** [comment]
The project https://github.com/NewSignature/us-map has a nice svg map with pulled out boxes for the smaller states.  Maybe implement that map into this project.

**Comment by manifestinteractive** [comment]
These maps are generated by a third party application ( as mentioned in the docs ).  If they are generated incorrectly, there is nothing anyone can do about it.
