### ISSUE TITLE
Width and height of jQuery Vector map not getting set

### ISSUE THREAD

**Issue by amirtcheva** [manifestinteractive/jqvmap#109]
I'm running Rails 4, 
I have the following .js:
jQuery('#vmap').vectorMap({ map: 'usa_en'})   

And in my view I have:
<div id="vmap" style="width: 600px; height: 400px;"></div>  

Both jquery.vmap.usa.js/jquery.vmap.js and jqvmap.css files are being included (in my assets folder), however, I get the following error when I run:

__Error: Invalid value for <svg> attribute width="null" jquery.vmap.js?body=1:126__
VectorCanvas.setSize jquery.vmap.js?body=1:126
VectorCanvas jquery.vmap.js?body=1:114
WorldMap jquery.vmap.js?body=1:392
$.fn.vectorMap jquery.vmap.js?body=1:70
(anonymous function) vmap.js?body=1:1
__Error: Invalid value for <svg> attribute height="null" jquery.vmap.js?body=1:127__
VectorCanvas.setSize jquery.vmap.js?body=1:127
VectorCanvas jquery.vmap.js?body=1:114
WorldMap jquery.vmap.js?body=1:392
$.fn.vectorMap jquery.vmap.js?body=1:70
(anonymous function) vmap.js?body=1:1

**Comment by Badspeed** [comment]
Same issue here, any fix for this?

**Comment by manifestinteractive** [comment]
@ghost has it correct, you cannot get the width and height of an element during page load, which your code was likely running during.  You can either put your script in your body tag, or use an onload event handler.
