### ISSUE TITLE
Add some other people to keep repo going

### ISSUE THREAD

**Issue by billpull** [manifestinteractive/jqvmap#111]
Seeing that there hasn't been a commit for quite awhile on this project
but there are a lot of open Issues as well as PRs for common problems
would be great if someone could maybe add some new maintainers.

**Comment by manifestinteractive** [comment]
If you are volunteering, I will add you as a contributor ;)  I moved cross country last year and started a new job, so stuff got crazy busy.  Getting caught up now and have all the PR's that could be merged integrated.  Going through issues now to do cleanup.
