### ISSUE TITLE
How to add a pin on the map

### ISSUE THREAD

**Issue by mushtaqak** [manifestinteractive/jqvmap#113]
Hi, How can I add the pin and tooltip on clicked country.  Additionally I want to draw the line between two pins ? please guide me. Thanks in advance.

P.S: I really like this map plugin, helped me a lot.

**Comment by mushtaqak** [comment]
@maeishoj Here you go man https://github.com/mushtaqak/fancyWorldMap . Cheers

**Comment by maeishoj** [comment]
Awesome! Cheers!
