### ISSUE TITLE
How to get Mouse Position

### ISSUE THREAD

**Issue by darker4ever** [manifestinteractive/jqvmap#114]
Hi!

I can't get the pageX and pageY property events of the mouse (undefined value), in the "onRegionOver: function (event, code, region) {" at $('#vmap').vectorMap({

I need to show a div at the mouse position with region information when the mouse moves over a region.

Thank you very Much!

**Comment by rjbrooksjr** [comment]
I had the same problem, but @ArtemFitiskin's solution worked for me.

**Comment by manifestinteractive** [comment]
This is an interesting idea, anyone want to make this a PR using the current master branch ?

**Comment by manifestinteractive** [comment]
OK, I am closing this ticket as a solution is present for those that want it.  I am not sure this is something that needs to be integrated into the main project.
