### ISSUE TITLE
onregionover hovercolor change

### ISSUE THREAD

**Issue by price2b** [manifestinteractive/jqvmap#116]
dear all, I have one implementation in mind but i cannot make it work:

onRegionOver:function(event, code, region){
                    if (code == "us" ||
                        code == "ca" ||
                        code == "br" )
hoverColor: '#F99A13'
}
does anyone know what can I do to override the hovercolor only for the selected countries when the mouse is over the country defined at it condition if?.
brgds

**Comment by manifestinteractive** [comment]
This is not something currently supported.  Closing due to age.
