### ISSUE TITLE
Mouse Drag map release issue

### ISSUE THREAD

**Issue by MashB** [manifestinteractive/jqvmap#118]
Any help to solve this issue will be appretiated 
Repro steps below
1) Zoom the map to  3-4 levels.
2) Drag the map 
3) While dragging map move the cursor out of map area ( out of map frame) and release the cursor (mouseup)
4) Now just move the cursor back into map area , you see the cursor is not released yet , it still holds the mouse down event.

**Comment by manifestinteractive** [comment]
This is now addressed in https://github.com/manifestinteractive/jqvmap/tree/issue-118

Please let me know if this works for you.  I will merge this into master soon if I do not hear anything, as it works with all major tested browsers, but I wanted to give you the ability to test it first.

Sorry it took a while to get this looked at, I moved cross country a while ago and took on a new job ... so things got kind of crazy for a bit.

**Comment by manifestinteractive** [comment]
This now has PR #187
