### ISSUE TITLE
Destroy Map?

### ISSUE THREAD

**Issue by sonicparke** [manifestinteractive/jqvmap#12]
Is there a way to destroy a map using and event handler? I'd like to be able to dynamically load a map based on user click.

**Comment by chrisNom** [comment]
I also needed to update the map, based on user interaction and none of the solutions above helped me. 
Instead I just "empty" the map's div before calling the vectorMap():

               `// remove the old data from map
                $('#vmap').empty();
                
                // and then render map
                $('#vmap').vectorMap({
                    map: 'world_en',
                    backgroundColor: null,
                    color: '#ffffff',
                    hoverOpacity: 0.7,
                    selectedColor: '#666666',
                    enableZoom: true,
                    showTooltip: true,
                    values: sample_data,
                    scaleColors: ['#C8EEFF', '#006491'],
                    normalizeFunction: 'polynomial',
                    onLabelShow: function (event, label, code) {
                        if (sample_data[code] > 0)
                            label.append(': ' + sample_data[code]);
                    }
                });`
