### ISSUE TITLE
Macau is missing

### ISSUE THREAD

**Issue by davidangel** [manifestinteractive/jqvmap#121]
It would be nice if Macau could be separate on the world map:
http://countrycode.org/country_detail.cfm?countryid=140

**Comment by vpakg** [comment]
Macau is not really a country, though.

**Comment by davidangel** [comment]
Is it not?

**Comment by manifestinteractive** [comment]
These maps are generated by a third party application ( as mentioned in the docs ).  If they are generated incorrectly, there is nothing anyone can do about it.  Though it sounds like this might not actually be an issue.
