### ISSUE TITLE
Jammu and Kashmir missing in India map (worldmap)

### ISSUE THREAD

**Issue by vasekkunes** [manifestinteractive/jqvmap#125]
Hello,

according to ie. http://en.wikipedia.org/wiki/File:India-locator-map-blank.svg Jammu and Kashmir is regular part of India. In detailed India map is correct while in worldmap isn't.

Would be nice & fair to India people if this can be fixed. I would do that myself, but I'm too busy to study any guide right now.

Thanks to authors of this nice map anyway

**Comment by surajgujar** [comment]
@manifestinteractive :100:  Can you please make this changes ASAP..??

**Comment by manifestinteractive** [comment]
I do not have control of how the maps are generated.  They are created from GeoLocation data as mentioned in the README file.  If you would like to update the maps, this is something you'll need to do outside this project.

**Comment by vasekkunes** [comment]
I tried to use map definitions from http://jvectormap.com/ , in the end I switched to http://jvectormap.com/ completelly. A tutorial on how to quickly generate map files from geo data would great. Thank you for your effort anyway, nice project.
