### ISSUE TITLE
Map not resizing for iphone only

### ISSUE THREAD

**Issue by padstow** [manifestinteractive/jqvmap#132]
Hello,

I have a world map that is acting responsively on desktop browsers and iPad, but not on iPhone -- I've tried setting max-height and max-width !important on either/both the containing div and the svg in my media queries, but the map is still rendering way too large for the iphone viewport (so is cut off.)  I have the same meta viewport & apple-mobile tags as on the jqvmap website, as far as I can tell I have everything set up according to documentation - what am I missing??

**Comment by clintLandrum** [comment]
@padstow Are you using viewBox and preserveAspectRatio attributes on your svg element?

**Comment by manifestinteractive** [comment]
JQVMap does not automatically resize, however, we do handle this on our own website.  You can see how we do this in the http://jqvmap.com/js/site.js file's `resizePage` page function.

**Comment by ptliko** [comment]
is there any online demo to test resize for responsive?
