### ISSUE TITLE
Compatibility issue with sugar.js

### ISSUE THREAD

**Issue by pixxelfactory** [manifestinteractive/jqvmap#133]
First of all: great script, i love it, it is much simpler and easy to use than other vector-map scripts!

Now, i discovered a little problem:
When the plugin is loaded onto a page where sugar (http://sugarjs.com/, latest version) is included,
it throws an error:
this.countries[code].setFill is not a function
This bug can be reproduced with the standard world-map example wich is included in the zip-package.

Thanks again for this great script!

**Comment by manifestinteractive** [comment]
Please verify if this is still an issue with v1.1.0
