### ISSUE TITLE
Highlight a country when hover a name

### ISSUE THREAD

**Issue by mluce194** [manifestinteractive/jqvmap#135]
I have a list of countries below the map as shown here:

<div id="links"><ul><li><a href="CH" onclick="return false;">Switzerland</a></li><li><a href="FR" onclick="return false;">France</a></li></ul></div>

Is it possible to have my listed countries highlight on the map when I hover their name on the list?

**Comment by manifestinteractive** [comment]
This would require you to write custom software to do this.  JQVMap does not currently support this.
