### ISSUE TITLE
Add an auto zoomIn After load or as default

### ISSUE THREAD

**Issue by sagive** [manifestinteractive/jqvmap#142]
Hey, LOVE THE PLUGIN ;)

i would like to start with a zoomin (simulating a click on the button) - is it possible to 
do so as soon as the map loads or as default?

i tried this:
'$("#vmap").vectorMap().zoomIn();'

but i guess i am way off.. checked the apiEvents but couldnt find "on load"

Suggestions?

**Comment by manifestinteractive** [comment]
All you need to do is run the following:

```js
jQuery('#vmap').vectorMap('zoomIn');
```

Likewise you can zoomout the same way:

```js
jQuery('#vmap').vectorMap('zoomOut');
```

See https://github.com/manifestinteractive/jqvmap#functions for more details

**Comment by sagive** [comment]
thanks mate ;)
