### ISSUE TITLE
Show country code inside country

### ISSUE THREAD

**Issue by sagive** [manifestinteractive/jqvmap#147]
how can i show the country code inside the country area using jquery or other method?
Searched and searched but couldnt find any example, explenation...

**Comment by archanarajput6** [comment]
Is there any way I can add two digit ISO country code to a US map, I've 
enableZoom: false

<div id="vmap" style="width: 800px; height: 500px;"></div>

Here's a div with height and width. Need urgent help.

**Comment by manifestinteractive** [comment]
This seems like something that will need to be custom build.  It is not currently supported.
