### ISSUE TITLE
multi selection and minified versions of jqvmap

### ISSUE THREAD

**Issue by pastorello** [manifestinteractive/jqvmap#153]
Hi,
I checked your multi.html sample, the result is:
1) samples/multi.html does not work, regions are not colored and if I change   
selectedRegion: 'FR'
to
selectedRegion: ['ES','FR']
the result remains the same.

2) if I try to use minified versions of the js, I get an error (either jquery.vmap.min.js and jquery.vmap.packed.js)
TypeError: params.selectedRegion.toLowerCase is not a function
jqvmap-stable/jqvmap/jquery.vmap.min.js
Line 12
(Chrome says: Uncaught TypeError: undefined is not a function)

**Comment by manifestinteractive** [comment]
This issue has been resolved in the latest release ( v1.1.0 ).
