### ISSUE TITLE
Please Correct Indian MAP

### ISSUE THREAD

**Issue by surajgujar** [manifestinteractive/jqvmap#155]
Hello,

according to ie. http://en.wikipedia.org/wiki/File:India-locator-map-blank.svg Jammu and Kashmir is regular part of India. In detailed India map is correct while in worldmap isn't.

Would be nice & fair to India people if this can be fixed. I would do that myself, but I'm too busy to study any guide right now.

Thanks to authors of this nice map anyway

**Comment by manifestinteractive** [comment]
I do not make the maps, they are generated by a program ( as mentioned in the documentation ).  If the program generated the map incorrectly, there is nothing I can do to fix that.
