### ISSUE TITLE
Brazil map has an unexpected end of file.

### ISSUE THREAD

**Issue by alexrayan** [manifestinteractive/jqvmap#157]
Seems like Brazil map (jquery.vmap.brazil.js) has an unexpected end of file in the repo: https://raw.githubusercontent.com/manifestinteractive/jqvmap/stable/jqvmap/maps/jquery.vmap.brazil.js

Wonder if the file got corrupted at some point? It ends with coordinates, but it should end with ...","name":"Brazil"}}});

Including the file produces "Unexpected token ILLEGAL" issue.

Best regards,
Alex

**Comment by valdeir2000** [comment]
True, the file is incomplete.

**Comment by manifestinteractive** [comment]
This issue has been resolved in the latest release ( v1.1.0 ).
