### ISSUE TITLE
Update documentation for scaleColors

### ISSUE THREAD

**Issue by jenlampton** [manifestinteractive/jqvmap#162]
```
**scaleColors** *['#b6d6ff', '#005ace']*

This option defines colors, with which regions will be painted when you set option values. Array scaleColors can have more then two elements. Elements should be strings representing colors in RGB hex format.
```

I've read and re-read this docblock for `scaleColors` but can't for the life of me figure out what this value is supposed to do.  What I want it to do is color all my regions using a random selection from this set. That doesn't seem to be the case, however. 

What does `when you set option values` mean, and how does one do that?  I also checked the docs and couldn't find any further explanation on that either.

I'll be happy to file a PR with a rewrite of this docblock if someone can explain to me what is supposed to be happening with `scaleColors`.

(also 'then' should also be 'than' in the docblock above)

**Comment by jenlampton** [comment]
Maybe it doesn't work for the USA map?

**Comment by manifestinteractive** [comment]
`scaleColors` was used for adding statistical weight to regions.  The sample located at https://github.com/manifestinteractive/jqvmap/blob/master/samples/world.html uses the file `./data/jquery.vmap.sampledata.js` to generate stats.  There is no way to make random colors as you requested.
