### ISSUE TITLE
Brazilian map visualization error 

### ISSUE THREAD

**Issue by BenevidesLecontes** [manifestinteractive/jqvmap#164]
I'm trying to work with vmap, maps like USA, Algeria, Germany and others are working properly. But when i'm trying to use Brazil map, it does not appear. See the screenshots, USA map draw, but the Brazil map don't.
![screen shot 2015-06-29 at 10 31 42 am](https://cloud.githubusercontent.com/assets/1839361/8408903/231b6d0a-1e4a-11e5-991e-6321dfee6bcc.png)

![screen shot 2015-06-29 at 10 33 24 am](https://cloud.githubusercontent.com/assets/1839361/8408931/5b448ba8-1e4a-11e5-83d1-d67ffe4138ef.png)

Errors in the console
![screen shot 2015-06-29 at 10 27 50 am](https://cloud.githubusercontent.com/assets/1839361/8408821/a298acba-1e49-11e5-9cbf-7c25494f3731.png)

**Comment by manifestinteractive** [comment]
This issue has been resolved in the latest release ( v1.1.0 ).
