### ISSUE TITLE
1/2 of Latvia is occupied by Russia... WHY?

### ISSUE THREAD

**Issue by valdistt** [manifestinteractive/jqvmap#165]
Latvia is displayed wrong - all Western part of Latvia is marked and Russia. It could be a bad joke, but not in this geopolitical situation, when Russia aggressively acts against their neighbour countries. I understand, that there was planned to place Kaliningrad, but in real live it's located multiple hundred km to south. And because of that you should not take away territories of Latvia!
Please, fix the issue, if you are not supporting Russian agression!

**Comment by alekspol74** [comment]
Да ладно, подумаешь чуть чуть Латвии, агрессия России это конечно страшная штука, такая страшная сказка, злой агрессивный медведь, но это уже от интеллекта зависит, от умения анализировать информацию

**Comment by manifestinteractive** [comment]
These maps are generated by a third party application ( as mentioned in the docs ).  If they are generated incorrectly, there is nothing anyone can do about it.
