### ISSUE TITLE
How i could add specific colors to specific countries

### ISSUE THREAD

**Issue by anahitdev** [manifestinteractive/jqvmap#170]
I need to create the world map countries with some specific colors.How i can add specific color to the specific country?

**Comment by benjaminkalk** [comment]
I may not be correct in this, but I think that you are supposed to be able to use color setting with an objects where the keys are the region code.  For ex:  { 'ny' : '#c9dfaf', 'tx' : '#818181'}

**Comment by manifestinteractive** [comment]
You can do this easily with JavaScript via:

```js
jQuery('#vmap').vectorMap('set', 'colors', { 'us': '#0000ff' });
```

In that example, I am setting the country with the code `us` to the color `#0000ff`

**Comment by manifestinteractive** [comment]
but, yes, as @benjaminkalk mentioned, you can also set this as a param in the config:

```js
jQuery('#vmap').vectorMap({
    map: 'world_en',
    backgroundColor: '#333333',
    color: '#ffffff',
    colors: { 
        'us': '#0000ff' 
    },
    selectedColor: '#666666',
    enableZoom: true,
    showTooltip: true
});
```
