### ISSUE TITLE
Disable clicking on the 'country'

### ISSUE THREAD

**Issue by huglester** [manifestinteractive/jqvmap#173]
Hello,

I wonder if there is a way to disable 'clicking' on the map?
Because I don't want use clicking the map, deselect all items in selectedRegions

THank you

**Comment by andkramer** [comment]
Please be more specific. Do you want regions not selectable? The whole map static and noninteractive like an image? I would like to help :)

**Comment by huglester** [comment]
Hello @andkramer , I would like Country Names to be shown when hovering a country. But I want it make impossible to click on the country, so it does not 'select' only that specific country :)

**Comment by manifestinteractive** [comment]
@huglester and @andkramer you may be able to use the `onRegionClick` method to prevent the click event from being fired.  Might require an update to the code base to pass in the event so it can be stopped.

**Comment by manifestinteractive** [comment]
@huglester just out of curiosity, would just setting the color of a region be helpful to you ( vs selecting it ? ).  Issue #170 has some examples of how to do this.  Basically, you can use the `colors` property to assign custom colors to regions.  It's different than having them selected and just gives the region a custom color.  You an still select / deselect whatever regions you want, but the custom color will stay just as you want it.

The only issue you would have then is if the selected region color is different than the custom color you picked for your region.  Selecting the custom colored region would change the color to the `selectedColor` property.  Deselecting it would put it back to the color you set in `colors`.

**Comment by manifestinteractive** [comment]
Greetings @huglester, I was wondering if the example I just released in https://github.com/manifestinteractive/jqvmap/blob/master/examples/usa.html might be what you are looking for.  It's basically a configuration that makes certain regions a specific color and disables selection & hover colors.

**Comment by manifestinteractive** [comment]
Closing this ticket out.  The example file listed in the above comments satisfies the requests being made for this specific issue.
