### ISSUE TITLE
Map is blank after updating from 1.0 to 1.1

### ISSUE THREAD

**Issue by a1xon** [manifestinteractive/jqvmap#174]
Hi!
First thank you very much for sharing this awsome project!
I "updated" today from 1.0 to 1.1 but the scale colors are not appearing. I did not change my code, just the files in the jqvmap folder. The map also has all information but is blank. 
Also I noticed that the sample map on http://jqvmap.com/ is blank too!

Anybody else with the same problem?

(Firefox 41.0.2, Windows 7)

**Comment by carasik** [comment]
Also have the same problem

**Comment by manifestinteractive** [comment]
I do not have a windows machine to test this with, however, I have verified that this works on Firefox, Safari, Chrome & Opera on OSX.  Seems like it might be a specific issue with Windows.

Any way you can output the Javascript Console for Error Messages?

**Comment by a1xon** [comment]
Yes. No Errors for me. On Android Chrome the sample map on your website is blank too.

**Comment by a1xon** [comment]
http://browsershots.org/http://jqvmap.com/
=> no scale colors on every tested system. 1.1 and 1.2.
If there anything I could do to help you? Can't find any semantic errors in the code..

**Comment by manifestinteractive** [comment]
FYI, I am currently installing VM's for this issue ( I had to get windows licenses ).  I am also purchasing a specific windows tablet to make sure this works on an actual piece of hardware ( I don't always trust VM's as they have lied to me on more than one occasion ).

I have started a new branch ( https://github.com/manifestinteractive/jqvmap/tree/windows-fix ) that I will be working off of for those wanting to test.  I will post an update to this thread once I have something to test.

Currently this new branch is identical to master.

**Comment by a1xon** [comment]
Thank you very much. Is there anything I can help you with - just let me know. May I buy you a beer for your awesome work?

**Comment by manifestinteractive** [comment]
ha ha, no ... something broke and it's my job to fix it.  Enough people are using this project that it's unacceptable for this to be broken on a modern browser.  I just did not have a direct way to recreate it and develop a fix for it without recreating the environment to work in.

Trying to tackle all the big asks on this project too ( just added the ability to create custom maps now in v1.3.0 ).  Once I get this Windows bug fixed I will make a patched release and hopefully start knocking out other feature requests ASAP.  Starting with the mobile / responsive stuff.

**Comment by manifestinteractive** [comment]
@a1xon & @carasik So I just tested this on Window 7 running Firefox 42 ( latest version ) and everything worked just fine.  Can you please clarify if you are using a specific Service pack or something ?

See the screenshot below where I am literally on a Window 7 Machine with Firefox open.  Version numbers for OS & Browser also open for proof.

<img width="2004" alt="screen shot 2015-12-05 at 12 31 47 am" src="https://cloud.githubusercontent.com/assets/508411/11606228/a4539798-9ae7-11e5-8296-b20d9b5431d7.png">

**Comment by a1xon** [comment]
As I said the map looks great! But the colors are missing. Even in your picture :) All countrys are white. The scale colors don't apply..

**Comment by manifestinteractive** [comment]
Colors work fine too.  There are no colors on that first map.  The USA Map however does have colors as shown in this screenshot.

<img width="2004" alt="screen shot 2015-12-05 at 12 45 30 am" src="https://cloud.githubusercontent.com/assets/508411/11606284/b4a547de-9ae9-11e5-885e-f56d45e4f21a.png">

If you want to set colors for a region on load, you have to set the `colors` option.

```js
jQuery('#vmap').vectorMap({
    map: 'usa_en',
    backgroundColor: null,
    color: '#ffffff',
    enableZoom: true,
    showTooltip: true,
    selectedColor: null,
    hoverColor: null,
    colors: {
        mo: '#666666',
        fl: '#666666',
        or: '#666666'
    },
    onRegionClick: function(event, code, region){
        event.preventDefault();
    }
});
```

In this example I specifically set the colors for Missouri, Florida & Oregon ( the state's I've lived in while working on this project :P )  `scaleColors` only sets colors based on the values param.  You can see the example of this in the https://github.com/manifestinteractive/jqvmap/blob/master/examples/continents.html by looking for `sample_data`.  I am actually going to remove `scaleColors` from the online example as it does not actually get used in, and probably is confusing.

Please let me know if actually fixes your issue for colors not working for you.

**Comment by manifestinteractive** [comment]
actually scratch that, the issue is that scaleColors is actually not working AND it is supposed to be using it from sample_data.  I did not see that being included in the demo, so I just thought it was setting the colors for scale, without providing the data.

Totally misunderstood the issue here.  This is actually broken then on all browsers.

Looking into it now.  Sorry for the confusion.

**Comment by a1xon** [comment]
Thank you very much. Guess my error descripton was too fuzzy...

**Comment by manifestinteractive** [comment]
Yep, it is fixed now and in master :)  I actually completely forgot about that coloring.  Looks like an old PR actually reversed the logic so ANY value for a scale set it to the defuult fill color.  I was able to track down the old code and restore that section, and works perfectly again.

<img width="2004" alt="screen shot 2015-12-05 at 12 45 30 am" src="https://cloud.githubusercontent.com/assets/508411/11606403/532a17d2-9aee-11e5-8200-6ec91d5d12f2.png">

If you can verify 1.3.1 works for you, I will close this issue.

**Comment by a1xon** [comment]
Can't check if it's working in my project at the moment. But works for me at your website on mobile chrome and firefox windows 7 & 10. Will reply tomorrow if the "update" worked. Thank you a lot!

**Comment by manifestinteractive** [comment]
Cool, make sure to check the CHANGELOG.md file, as v1.3.1 maps had a slight change to them ( one letter ) that means you will need to update you map files too, so you can't just swap out the main plugin and keep your own files.

For those curious, all the changed was the word 'pathes' was misspelled and has been corrected to 'paths' ( this was always how it was spelled before I ported it over ).  This fix now makes all the map files from the other vector project compatible with ours, and visa-versa.  With the map creator working on ours now, people can share their maps on both projects if they wanted.  

Was worth breaking the older maps for that portability between projects.

**Comment by a1xon** [comment]
Thank you very much! Everything works fine now.

**Comment by carasik** [comment]
Thanks a lot for you work!! My project looks great again:)
