### ISSUE TITLE
Russia\Ukraine map

### ISSUE THREAD

**Issue by Guardpc** [manifestinteractive/jqvmap#179]
Good afternoon!
First of all, thank you for the map of Russia.
But why on this map Republic of Crimea is not part of the Russian Federation? 
When you plan to correct the inaccuracies in the maps?

**Comment by manifestinteractive** [comment]
@Guardpc as mentioned in the https://github.com/manifestinteractive/jqvmap/blob/master/CONTRIBUTING.md#map-specific-issues file

"Please note that the JQVMap team does not make the maps, nor will we make any modifications to maps that have been contributed. If there is an issue with the map, you are more than welcome to update the map within your project."

The maps are generated by a third party python script and no one on this team actually makes these maps, they are often contributed by users like yourself.  You are more than welcome to update this file and submit a Pull Request.
