### ISSUE TITLE
Borders on regions that overlap are considerably thicker than they should be

### ISSUE THREAD

**Issue by gf3** [manifestinteractive/jqvmap#18]
Example:

![Screenshot](http://f.cl.ly/items/0Y1r261Q2T1n2L2L1T3f/Screen%20Shot%202012-06-22%20at%205.06.11%20PM.png)

This map has an explicit `borderWidth` of `1` as well as a `borderOpacity` of `1`. As you can see, the interior borders look to be ~3px in width, while the outer ones are 1px as intended.

**Comment by jenlampton** [comment]
I'm having similar issues on Chrome, where FF and Safari look great. Chrome doesn't seem to honor the opacity setting and also has trouble drawing the borders correctly. 

Chrome 42.0.2311.135 (64-bit)
![chrome](https://cloud.githubusercontent.com/assets/397895/7506256/d3ecb62a-f41a-11e4-93fe-48674ad1f744.png)

FF and Safari 
![ff](https://cloud.githubusercontent.com/assets/397895/7506262/d917bc12-f41a-11e4-81d6-c5286d696fc1.png)

Here are my settings:
```
jQuery(document).ready(function() {
    jQuery('#vmap').vectorMap({
        map: 'usa_en',
        backgroundColor: '#ffffff',
        borderColor: '#000000',
        borderOpacity: 1,
        color: '#E7E7E7',
        hoverColor: '#2c7cb4',
        selectedColor: '#22608b',
        enableZoom: false,
        showTooltip: true
    });
  });
```

**Comment by jenlampton** [comment]
Changing the border color from white to black makes the differences in widths easier to see:
Chrome 
![chrome2](https://cloud.githubusercontent.com/assets/397895/7506278/231bd4a6-f41b-11e4-989d-7811f221302e.png)

FF & Safari
![ff2](https://cloud.githubusercontent.com/assets/397895/7506281/27f9d694-f41b-11e4-9543-4c5595a83628.png)
