### ISSUE TITLE
Regions is missing South Sudan(SS)

### ISSUE THREAD

**Issue by jjrchrds** [manifestinteractive/jqvmap#181]
South Sudan is currently included as part of Sudan. I'm requesting that this be changed, and South Sudan be its own country. 

Thank you

**Comment by manifestinteractive** [comment]
As mentioned in the CONTRIBUTING.md file, we do not create or alter the map files.  These are managed outside of the project.  If you want this file changed, you will have to use the third party tools that created the maps and recreate them on your local development machine.
