### ISSUE TITLE
Support for IE8

### ISSUE THREAD

**Issue by CalumBaines** [manifestinteractive/jqvmap#183]
Hi

Just wanted to check if this plugin was supported in IE8?
I have seen a couple of previous comments mentioning IE8, but obviously SVG isnt supported so wasn't sure.

I am using the world map and getting the error below:
**SCRIPT438: Object doesn't support property or method 'pathSvgToVml'**

Thanks in advanced for your help.

**Comment by zhuangya** [comment]
according to https://support.microsoft.com/en-us/gp/microsoft-internet-explorer

i personally don't think we should/need to support IE 10- anymore.

sorry about that dude.

also: http://meowni.ca/is-ie10-dead/

**Comment by manifestinteractive** [comment]
@CalumBaines Agreed, with the VERY small team working on this project, it will be impossible to maintain support for older browsers.  As such, I am choosing to only support "modern browsers" running relatively new versions.  In general, I try to support the same browsers as https://support.google.com/a/answer/33864?hl=en as they tend to set the trend for what other projects choose to support.
