### ISSUE TITLE
Updating country colours from a Javascript

### ISSUE THREAD

**Issue by andreasspeck** [manifestinteractive/jqvmap#192]
I am trying to update the colours of ALL countries when some selects a year in a year selector above the map. What is working is the following:

1.) I get a long string with the format "code: 'htmlcolour', code: 'htmlcolour' ... "
This string seems to be correct. In fact, I do update the colours after initialising the map calling jQuery from php and getting that string in (jQuery('#vmap').vectorMap('set', 'colors', { thelongstring } );

However, this is not working from my Javascript. 

I actually had two problems here:
1.) My world map is called "world_en_merc" (or was). This worked fine when I was updating the colours making the call to jQuery from my php script. 
However, trying to do the same from my Javascript it complained that world_en was not initialised - obviously not, as I initialised a map called world_en_merc. This error went away when I changed the name of the map to world_en.
2.) I can call jQuery('#vmap').vectorMap('set', 'colors', { us: '#000000' } ); from my Javascript, and that works. However, it does not work when I try to put in the string variable:
- jQuery('#vmap').vectorMap('set', 'colors', { mystringwithallcodes } );
- jQuery('#vmap').vectorMap('set', 'colors', mystringwithallcodespluscurlybrackets );
- jQuery('#vmap').vectorMap( mystringwithalltheabove );

Any ideas?

**Comment by a1xon** [comment]
I guess this needs to be an array with objects not a simple string.

**Comment by andreasspeck** [comment]
Well, this is my string:

ad: '#191a00', ae: '#191a00', af: '#191a00', ag: '#191a00', al: '#191a00', am: '#191a00', an: '#191a00', ao: '#191a00', ar: '#191a00', at: '#191a00', au: '#191a00', az: '#191a00', ba: '#191a00', bb: '#191a00', bd: '#191a00', be: '#191a00', bf: '#191a00', bg: '#191a00', bh: '#191a00', bi: '#191a00', bj: '#191a00', bn: '#191a00', bo: '#191a00', br: '#191a00', bs: '#191a00', bt: '#191a00', bw: '#191a00', by: '#191a00', bz: '#191a00', ca: '#191a00', cd: '#191a00', cf: '#191a00', cg: '#191a00', ch: '#191a00', ci: '#191a00', cl: '#191a00', cm: '#191a00', cn: '#191a00', co: '#191a00', cr: '#191a00', cs: '#191a00', cu: '#191a00', cv: '#191a00', cw: '#191a00', cy: '#191a00', cz: '#191a00', de: '#191a00', dj: '#191a00', dk: '#191a00', dm: '#191a00', do: '#191a00', dz: '#191a00', ec: '#191a00', ee: '#191a00', eg: '#191a00', er: '#191a00', es: '#191a00', et: '#191a00', fi: '#191a00', fj: '#191a00', fm: '#191a00', fr: '#191a00', ga: '#191a00', gb: '#191a00', gd: '#191a00', ge: '#191a00', gf: '#191a00', gh: '#191a00', gi: '#191a00', gl: '#191a00', gm: '#191a00', gn: '#191a00', gq: '#191a00', gr: '#191a00', gt: '#191a00', gw: '#191a00', gy: '#191a00', hk: '#191a00', hn: '#191a00', hr: '#191a00', ht: '#191a00', hu: '#191a00', id: '#191a00', ie: '#191a00', il: '#191a00', in: '#191a00', iq: '#191a00', ir: '#191a00', is: '#191a00', it: '#191a00', jm: '#191a00', jo: '#191a00', jp: '#191a00', ke: '#191a00', kg: '#191a00', kh: '#191a00', ki: '#191a00', km: '#191a00', kn: '#191a00', kp: '#191a00', kr: '#191a00', kw: '#191a00', kz: '#191a00', la: '#191a00', lb: '#191a00', lc: '#191a00', li: '#191a00', lk: '#191a00', lr: '#191a00', ls: '#191a00', lt: '#191a00', lu: '#191a00', lv: '#191a00', ly: '#191a00', ma: '#191a00', mc: '#191a00', md: '#191a00', me: '#191a00', mg: '#191a00', mh: '#191a00', mk: '#191a00', ml: '#191a00', mm: '#191a00', mn: '#191a00', mp: '#191a00', mr: '#191a00', mt: '#191a00', mu: '#191a00', mv: '#191a00', mw: '#191a00', mx: '#191a00', my: '#191a00', mz: '#191a00', na: '#191a00', nc: '#191a00', ne: '#191a00', ng: '#191a00', ni: '#191a00', nl: '#191a00', no: '#191a00', np: '#191a00', nr: '#191a00', nz: '#191a00', om: '#191a00', pa: '#191a00', pe: '#191a00', pf: '#191a00', pg: '#191a00', ph: '#191a00', pk: '#191a00', pl: '#191a00', pt: '#191a00', pw: '#191a00', py: '#191a00', qa: '#191a00', ro: '#191a00', rs: '#191a00', ru: '#191a00', rw: '#191a00', sa: '#191a00', sb: '#191a00', sc: '#191a00', sd: '#191a00', se: '#191a00', sg: '#191a00', si: '#191a00', sk: '#191a00', sl: '#191a00', sm: '#191a00', sn: '#191a00', so: '#191a00', sr: '#191a00', ss: '#191a00', st: '#191a00', sv: '#191a00', sy: '#191a00', sz: '#191a00', td: '#191a00', tg: '#191a00', th: '#191a00', tj: '#191a00', tl: '#191a00', tm: '#191a00', tn: '#191a00', to: '#191a00', tr: '#191a00', tt: '#191a00', tv: '#191a00', tw: '#191a00', tz: '#191a00', ua: '#191a00', ug: '#191a00', us: '#191a00', uy: '#191a00', uz: '#191a00', vc: '#191a00', ve: '#191a00', vn: '#191a00', vu: '#191a00', ws: '#191a00', ye: '#191a00', za: '#191a00', zm: '#191a00', zw: '#191a00'

**Comment by andreasspeck** [comment]
I finally managed it - I need to turn the string into an object.

1) I changed my php to give me a string with double quotes
2) I turn that into an object: var resultobj = eval("({"+result+"})");

And now I call jQuery('#vmap').vectorMap('set', 'colors', resultobj );
And it updates my colours!

**Comment by andreasspeck** [comment]
Just to mention: the problem with not recognising the name world_en_merc seems to have been related to errors being caused. Now also working.
