### ISSUE TITLE
Feature pull Request: Map of the Netherlands

### ISSUE THREAD

**Issue by idevit** [manifestinteractive/jqvmap#193]
Thanks for writing jqvmap :)
Added a pull request with the map of the Netherlands from wiki SVG:
@source http://upload.wikimedia.org/wikipedia/commons/d/d5/Provinces_of_the_Netherlands.svg

**Comment by manifestinteractive** [comment]
There is no pull request for this.  All pull requests are submitted through https://github.com/manifestinteractive/jqvmap/pulls

**Comment by manifestinteractive** [comment]
Closing this ticket, as once a pull request comes in it will start a new process and we can pick things up there :)
