### ISSUE TITLE
How do I get the list of selected regions?

### ISSUE THREAD

**Issue by joeframbach** [manifestinteractive/jqvmap#198]
I am using `multiSelectRegion: true`. After the user selects a few regions, I want to get the list of regions which are selected. How can I do this? I have tried something like `$('#states-map').vectorMap('get', 'selectedRegions')` since that was the syntax for `set`.

**Comment by joeframbach** [comment]
It seems that I can do:

```
var map = $('#states-map').vectorMap({
    map: 'usa_en',
    onRegionClick: function(element, code, region) {
        console.log(map.selectedRegions);
    }
})
```

However, the region is added to the list *after* onRegionClick is run. So the `map.selectedRegions` is not yet updated in the example above.

I could use `onRegionSelect` and `onRegionDeselect` to keep track manually, but that would just be a duplication of data and I would rather have the map be the source of truth.

---

Here is one way I got this to work, which is pretty hacky:

```
var map = $('#states-map').vectorMap({
    map: 'usa_en',
    onRegionClick: function(element, code, region) {
      setTimeout(function () {
        console.log(map.selectedRegions);
      }, 0);
    }
})
```

**Comment by manifestinteractive** [comment]
Hey @joeframbach, this is not a feature that exists, though it probably would be a handy one.  Even to keep track of single selections.  Just basically a getSlectedRegions or something.  I believe `map.selectedRegions` will just return whatever you set selectedRegions to during init, though I might be mistaken.  It's been awhile since I last looked into that part of the code.  I am working on another issue that puts me in that space, so I will see if this is something easy to add on.

**Comment by manifestinteractive** [comment]
@joeframbach OK, so after digging into this, `map.selectedRegions` is exactly what you should be using, and it's actually working 100%.

The reason your code is not working, when you stop to think about it, is that you are adding the code on `onRegionClick` which is the event that happens right before the click is processed.  This means the click is not actually registered until AFTER everything in your click handler is processed.  Which makes sense that your `setTimeout` works too, as it is technically firing right after the `onRegionClick` fires.

There is another method that you should probably be using to check for selected regions:

```js
var map = $('#states-map').vectorMap({
    map: 'usa_en',
    onRegionClick: function(element, code, region) {
      // don't check for selection change here
    },
    onRegionSelect: function(event, code, region){
        // Now we can get a correct list of selectedRegions
        console.log(map.selectedRegions);
    }
})
```

I have tested this with the current build and it works just like you want.  Even with `multiSelectRegion` enabled :)  Closing this ticket as resolved, but feel free to keep the dialog going if needed.  We can always reopen it if I misunderstood your issue.
