### ISSUE TITLE
onRegionSelect - region is undefined

### ISSUE THREAD

**Issue by D1M** [manifestinteractive/jqvmap#201]
onRegionClick: function(element, code, region) - region is defined.
onRegionSelect: function(element, code, region) - region is undefined for all codes.

**Comment by the-vector** [comment]
@D1M 
Write it on the line 468
`regionClickEvent = $.Event('regionClick.jqvmap');`
After
`jQuery(params.container).trigger('regionClick.jqvmap', [code, mapData.pathes[code].name]);`

**Comment by manifestinteractive** [comment]
Looks like something got lost there, I will take a look into why this did not get passed over.

**Comment by manifestinteractive** [comment]
Can you verify if this issue is resolved in this branch ?

https://github.com/manifestinteractive/jqvmap/tree/v1.5.0_prerelease

**Comment by the-vector** [comment]
@manifestinteractive
Doesn't work. It's my project [my_repository](https://github.com/the-vector/enviroment)
In the folder `'js/libs/jqvmap'`. working 'jquery.vmap.js'

**Comment by Thoum** [comment]
@manifestinteractive : Seems the issue is not solved, i still have the problem with the latest version.
The code is defined, but not the region.

**Comment by JeansReal** [comment]
Same problem here
