### ISSUE TITLE
Retrieve list of selected regions 

### ISSUE THREAD

**Issue by D1M** [manifestinteractive/jqvmap#202]
Can't find function or var to get all selected regions.  If you have multiSelectRegion: true,and user choose multiple regions it would be nice to have a function like getSelectedRegions() to retrieve list of selected regions like 'ru,fr,en'.

**Comment by manifestinteractive** [comment]
Turns out this is actually something we already do.

```js
var map = jQuery('#vmap').vectorMap({
    map: 'world_en'
});
```

Then you can access `map.selectedRegions` at any point to get an array of the selected regions.  Turns out there are a lot of exposed bits of data you can get this way.
