### ISSUE TITLE
Creating a map appends '-merc' suffix to map name.

### ISSUE THREAD

**Issue by bovender** [manifestinteractive/jqvmap#204]
When maps are created by the `create/jqvmap.py` script, a suffix `-merc` is automatically appended to the map name in the resulting javascript file. Of course the maps won't load if the name originally given in the json config file is used.

I saw this with two maps I [created](https://github.com/bovender/jqvmap). After manually removing the `-merc` suffix, I could load the maps all right of course.

Is this a bug or some feature, am I missing something?

**Comment by manifestinteractive** [comment]
This is likely how the map file is named and I just forgot to remove the suffix.  There is some code in there thats adding it, so simply removing the suffix should do the trick.  It might be a few days before I can look into this myself, but in the mean time, removing the suffix as you stated will solve the issue.

**Comment by bovender** [comment]
Thanks, I suspected as much. If I had time myself, I'd come up with a patch myself...
