### ISSUE TITLE
Bug with jquery.vmap.france.js for 2A and 2B departments

### ISSUE THREAD

**Issue by nelero** [manifestinteractive/jqvmap#206]
On mouseover and mouseclick for 2A and 2B (Corsica) script error occurs.
it's due to those specific departments which are not numerics.

In vmap.france.js, departments are told as "fr-2A" and "fr-2B".
But code on lines 164 and 201 says  code = code.toLowerCase();
so "fr-2a" and "fr-2b" are not found.

Please fix this by removing code = code.toLowerCase(); or fixing jquery.vmap.france.js file with lower departments declaration.

**Comment by manifestinteractive** [comment]
This has been fixed with a recent pull request merge.  Please download the latest from the master branch :)
