### ISSUE TITLE
Doesn't recognize Hong Kong (hk) country code

### ISSUE THREAD

**Issue by kamranzafar** [manifestinteractive/jqvmap#214]
The world map doesn't have Hong Kong, and it also doesn't recognize the country code (hk)

**Comment by manifestinteractive** [comment]
As mentioned in a few other map file tickets.  The maps are generated by a third party tool, which was not built by us.  It is a standard python toolset that generates these maps based on vector data combined with scale of overall items being placed into the map.  While obviously I agree that every country should be on the world map, if one is not, the only solution is for someone to make a new map file with this fixed.

Sadly, this will likely break other regions, as the map tool is actually not all that good ( to be honest ).  So getting everything 100% accurate is pretty much impossible.  This is the only reason I am closing this ticket, as getting everything accounted for in a world map is just not something I feel can be done at this time, using the current tools we have to do so.

If someone does want to work on this, I agree it needs to be done, but we will likely need to have everyone review the world map manually before pushing it to production to make sure that all size, shape & location issues are resolved for everything that should exist on that map ( which is actually quite a bit in a small space )
