### ISSUE TITLE
installable version for npm

### ISSUE THREAD

**Issue by t3easy** [manifestinteractive/jqvmap#217]
It would be nice to have an installable version as npm package without a grunt build task, because not everyone uses grunt.
Also the latest version available over npm repository is a fork with version 1.0.1.

**Comment by manifestinteractive** [comment]
I would love to offer this via NPM.  However, someone beat me to the punch on creating the NPM package and has not been keeping it up to date.  Since I was not the person that submitted it, I have been unable to have it updated.  I tried both contacting the person that created the NPM package itself, as well as someone within the NPM community to show I was the author.

Nothing seems to work there.  If you have any advice on that, I would love to keep the NPM package up to date.  But since someone else registered with the name, and has not been keeping it up to date, I am not quite sure how to work around that.

I can easily have a `dist` folder added to the project for no grunt requirements for those that just want to use it via NPM.  But I guess getting control back of the NPM package would be a first step.

**Comment by t3easy** [comment]
If you add the dist folder it would be possible to use the git repository as npm dependency for the moment.
`"jqvmap": "git://github.com/manifestinteractive/jqvmap.git#v1.4.0",`

**Comment by t3easy** [comment]
I got reply on an E-Mail:

> Hi Jan, 
> 
> Thanks for emailing. In this case, we can go through the package transfer process outlined in our disputes policy: 
> https://docs.npmjs.com/policies/disputes#tldr
> 
> Get the author email with npm owner ls <pkgname>
> Email the author, CC support@npmjs.com
> After a few weeks, if there's no resolution, we'll sort it out.
> Did you or manifestinteractive want to request ownership of jqvmap? Whoever is making the request, please go through those steps and we'll be here to help out. 
> 
> Thanks so much, 
> Stephanie

**Comment by manifestinteractive** [comment]
@t3easy Thanks for getting me that info.  I will work on knocking that out.  There is a 1.5.0 build that fixes some issues.  The library already generated a `dist/jquery.vmap.js` file, but I had it ignored for committing.  Not actually sure WHY I did that to be honest :P

**Comment by manifestinteractive** [comment]
@t3easy after looking back at previous releases, it looks like the `dist` folder has actually been apart of the repo for a while. Both the `bower.json` file and `package.json` file are also referencing the `"main": "dist/jquery.vmap.min.js"`

BTW, I just put out v1.5.0 if you are currently using 1.4 on a project, you might want to update to if you need fix some of the bugs mentioned in the release notes:  https://github.com/manifestinteractive/jqvmap/releases

In the mean time, I guess I will leave this ticket open until we have the NPM library updated :smile:

**Comment by t3easy** [comment]
OK, I see. But then you should remove the post install script from the package.json. If it fails, because grunt is not installed, the jqvmap is not available under node_modules/jqvmap.

**Comment by manifestinteractive** [comment]
This is now in the master branch.  Also removed `postinstall` via another PR.

**Comment by allochi** [comment]
Hi, NPM installation fails with this log, could you please advice, thanks.

```
2050 error Darwin 15.4.0
2051 error argv "/usr/local/Cellar/node/5.11.0/bin/node" "/usr/local/bin/npm" "i" "jqvmap" "--save"
2052 error node v5.11.0
2053 error npm  v3.8.6
2054 error code ELIFECYCLE
2055 error jqvmap@1.5.0 postinstall: `grunt build`
2055 error Exit status 99
2056 error Failed at the jqvmap@1.5.0 postinstall script 'grunt build'.
2056 error Make sure you have the latest version of node.js and npm installed.
2056 error If you do, this is most likely a problem with the jqvmap package,
2056 error not with npm itself.
2056 error Tell the author that this fails on your system:
2056 error     grunt build
2056 error You can get information on how to open an issue for this project with:
2056 error     npm bugs jqvmap
2056 error Or if that isn't available, you can get their info via:
2056 error     npm owner ls jqvmap
2056 error There is likely additional logging output above.
2057 verbose exit [ 1, true ]
```

**Comment by alex-pex** [comment]
@allochi try ```npm install --save github:manifestinteractive/jqvmap```
