### ISSUE TITLE
Singapore is not in the list of regions

### ISSUE THREAD

**Issue by Kenshino** [manifestinteractive/jqvmap#221]
So in jquery.vmap.world.js - there is no Singapore.

Is it because we're too tiny ? :(

**Comment by manifestinteractive** [comment]
Actually, that is the exact reason.  The software that generates the maps has some issues with scaling small stuff.  So Regions that are small often get ignored.  Certainly not something we chose to remove :P 

There is apparently a way to change the way the small stuff is handled, though I honestly have no idea how to do that.  The map creator is a combination of open source projects other people developed and the documentation is pretty much non existent.  I did the best I could to port it over and document what I understood of it in the `create` folder.

If you would like to create a better map that has Singapore in it, that would be the place to start, though its not something we can really help with here.
