### ISSUE TITLE
From 1.0 to 1.5 : following

### ISSUE THREAD

**Issue by saxrub** [manifestinteractive/jqvmap#224]
My initial discussion being closed (quikly), I add elements following in this new discussion.
The problem is solved and documented in the initial discussion. 
It was not necessary to make an enormous transformation of the file map.
The only brought modification was of translated into small letters all the characters composing the code of the path. 
You can try http://wnat.fr/france_map.1.5.html

**Comment by manifestinteractive** [comment]
Happy you found a solution that worked for your migration from the first version :)
