### ISSUE TITLE
USA map missing some states and text align issue

### ISSUE THREAD

**Issue by tmuks** [manifestinteractive/jqvmap#230]
USA map following states are missing following states:
Puerto Rico, Guam, Northern Marianas, United States Virgin Islands and American Samoa.

Also text(showLabel) alignment issue for states like FL, CA and some others too..
It makes center of svg and label is way out of that state boundary or shifted to some other states too.

**Comment by manifestinteractive** [comment]
As stated in your other issue, the labels do work but need some extra love.  We have a custom example already prepared for it at https://github.com/manifestinteractive/jqvmap/blob/master/examples/labels.html

Keep in mind that both labels and pins use the center of the BOX around a region.  Meaning if you drew lines at the farthest points at the top, right, bottom & left ... THAT is the actual shape that is being used to calculate center.  Almost no regions are going to be perfectly rectangular, so finding the exact center of a complex polygon is not what this library does.  It just displays maps with regions.  The `labels.html` example shows how you can tweak your label positions to compensate for their unique shapes.

**Comment by manifestinteractive** [comment]
In regards to the "missing states" there is always going to be something people want changed in a map.  This is why there is a `./create` tool for people that want to make custom maps.  That tool was not created by us ( no support offered ), but something made open source online for people like you that would like to make custom maps, or changes to existing maps.
