### ISSUE TITLE
Minify for jqvmap.css file

### ISSUE THREAD

**Issue by pvnr0082t** [manifestinteractive/jqvmap#232]
Hi @manifestinteractive ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team. We want to host this library.
We found that the files in `dist/maps` don't need to be minified but `jquery.vmap.js` and `jqvmap.css` need to be minified. 
Because the auto-updater in cdnjs doesn't support partial minification, is it possible to provide minified file of `jqvmap.css`? Thank you.

https://github.com/cdnjs/cdnjs/pull/7928
https://github.com/cdnjs/cdnjs/issues/7716

**Comment by manifestinteractive** [comment]
@pvnr0082t A new release of v1.5.1 addresses this issue :)  `npm install jqvmap` seems to be working without issue.

**Comment by pvnr0082t** [comment]
Thanks for your big help. :+1:
