### ISSUE TITLE
No width and/or heigth defined

### ISSUE THREAD

**Issue by osworx** [manifestinteractive/jqvmap#240]
Some maps (e.g. Iran, Irak) have no width and height defined.
This leads to an js.error and the maps will not be displayed.
Adding a simple check in the **jquery.vmap.js** (at initialisation) would solve such:

> if( mapData.width === undefined || mapData.width == '' || mapData.width == null ) {
	mapData.width = '680';
}
if( mapData.height === undefined || mapData.height == '' || mapData.height == null ) {
	mapData.height = '550';
}`

**Comment by manifestinteractive** [comment]
@osworx this is now fixed in the master branch.  No maps moving forward will be accepted without the correct dimensions.  All maps that were missing dimensions were corrected.  Thanks for reporting the issue.
