### ISSUE TITLE
onRegionClick preventDefault block onRegionDeselect

### ISSUE THREAD

**Issue by elmeerr** [manifestinteractive/jqvmap#248]
Hi,

I'm trying to limit my selection to only 3 states among all. When I have the 3 selected, I want that nothing happens.
To do that, I use the `onRegionClick `and, when I have my 3 states selected, I call `event.preventDefault `so nothing will happen.
The problem is, if I click in one region that is already selected and I have 3 states selected, because of my `event.preventDefault`, the `onRegionDeselect `function doesn't trigger, this way I can't reduce the number of selected states.

How can I solve this...any suggestions?

Hope that's clear...

**Comment by elmeerr** [comment]
So guys...I manage to solve my problem without using onRegionDeselect. Now it works with no problem. I'm closing this issue.

**Comment by manifestinteractive** [comment]
@elmeerr Thanks for closing out this issue.  Any chance you can share your solution for those that land on this page later having a similar issue?  I'm sure you know how it goes when you've scoured the internet for an answer to your problem and see someone asking the exact same question as you, just to read the answer is "I figured it out" without saying what they figured out :P 

Would love to prevent that here.

**Comment by elmeerr** [comment]
Of course @manifestinteractive I was going to do that but my head was so full of things that I forgot...I manage to solve just using onRegionClick:
```
onRegionClick: function (event, code, region) { 
 var index = scope.source.indexOf(region); 
     if (index >= 0 && scope.source.length <= 3) {
                scope.source.splice(index, 1);
     } else {
         if (scope.source.length < 3) {
                 scope.source.push(region);
           } else {
                 event.preventDefault();
           }
     }
}
```
explaining the code:
I'm using angular directive so...`scope.source` is the same thing that `selectedRegions` so,,,if the region I'm clicking is already selected (index >=0) and the limit is not my max number (`length <= 3`) I just deselect my region (`scope.source.splice(index, 1)`) otherwise, I check if I'm in the limit to add new regions (`length < 3`)...if yes, I add my region, else I call `event.preventDefault()` to stop the select action. 

Hope that's clear and sorry for my english.

Kind regards.

**Comment by manifestinteractive** [comment]
@elmeerr perfection 👍

**Comment by elmeerr** [comment]
@manifestinteractive As we are here, I'm using a lot of angularjs recently and manage to create a directive to simulates jqvmap specifically to this solution...but is was just a merge... so I thought to ask you about that: are you working on a angular-directive for jqvMap? I think it will be good. =]

**Comment by manifestinteractive** [comment]
@elmeerr I am not actually.  Though I do personally do a lot of Angular Projects.  It might be cool to spin up a separate repo to work on this.  If you would be interested in collaborating on this, we could setup something together.  I leave for my honeymoon and will be back after the 17th, and we can set something up that just imports this project as a dependency :)

If it is just me doing it, I probably would not start anything new just for this, but I definitely see the value in it.  But honestly, it can get a little overwhelming managing open source projects by yourself :P

**Comment by elmeerr** [comment]
I imagine how it is managing this repo all by yourself....so, I cannot put any efforts on this now because I'm working in another project. But, when I start this feature in my project, I think about to "transform" jqvmap in an angular directive and I probably will. I'll let you know when I start it...it's not for now but I really think that will be great to have this. So...enjoy your honeymoon and lets think about this subject another time. 

Kind regards
