### ISSUE TITLE
TypeError: jQuery(...).vectorMap is not a function

### ISSUE THREAD

**Issue by MPapst** [manifestinteractive/jqvmap#249]
Hi,

when trying to load jqvmap within an ASP.NET MVC page I am getting this error:
`TypeError: jQuery(...).vectorMap is not a function`
I tried various samples and even if I am copying one of the samples directly into my website, its not changing.
I tried jQuery versions from 1.8.x to 1.11.x.

Any suggestion?

Thank you

**Comment by MPapst** [comment]
solved.. sometimes it is just.. an additional jquery include at the bottom of the page :(

**Comment by ajvbartlett** [comment]
@MPapst what did you add to resolve the error?

**Comment by MPapst** [comment]
@ajvbartlett, sorry haven't seen your comment.
I missed to include the jQuery library correctly.
