### ISSUE TITLE
<svg> attribute width (and height): Expected length, "null".

### ISSUE THREAD

**Issue by ataylor2247** [manifestinteractive/jqvmap#252]
I have followed the instructions outlined in documentations. However, when I attempt to display the map, nothing is displayed, and I am receiving the following errors in my chrome console: 

Error: <svg> attribute width: Expected length, "null". _____ line jquery.vmap.js?ver=4.5.3:1267
Error: <svg> attribute height: Expected length, "null". _____ line jquery.vmap.js?ver=4.5.3:1268

I have attempted to add my own validation to the top of the VectorMap function, and although this makes the errors go away, the map still does not display.  Any ideas how to resolve this issue?

**Comment by amandablum** [comment]
Hey, what was your resolution? Same issue.
