### ISSUE TITLE
How do you make maps responsive? 

### ISSUE THREAD

**Issue by steverhodes10** [manifestinteractive/jqvmap#253]
I noticed that the maps in your website are responsive http://jqvmap.com/. I see you have a resize function in your jquery.vmap.js script, but my map is not resizing. I'm using the angular2 framework, is there a specific place I need to make sure I call the method?

**Comment by manifestinteractive** [comment]
there is both a responsive & mobile example in the examples folder:

https://github.com/manifestinteractive/jqvmap/blob/master/examples/

Pretty much every combination of how to use JQVMap is in there somewhere.

**Comment by steverhodes10** [comment]
Thank you! it works now
