### ISSUE TITLE
Problem with updating the label values

### ISSUE THREAD

**Issue by chrisNom** [manifestinteractive/jqvmap#264]
I display a world map and display the counter of my events per country using this:

```
$('#vmap').vectorMap({
  map: 'world_en',
  backgroundColor: null,
  color: '#ffffff',
  hoverOpacity: 0.7,
  selectedColor: '#666666',
  enableZoom: true,
  showTooltip: true,
  values: sample_data,
  scaleColors: ['#C8EEFF', '#006491'],
  normalizeFunction: 'polynomial',
  onLabelShow: function (event, label, code) {
    if (sample_data[code] > 0)
      label.append(': ' + sample_data[code]);
  }
});
```

You see, I use **onLabelShow** to append a counter on the country label (if it is >0)
So it displays something like this:
Italy: 16
But, when I reload the map, the labels get a new value along with their old one:
Italy: 16: 37
And it goes on adding the new counters on every reload!

How can I reset the map?

**Comment by AdrienCS** [comment]
What you mean by 

> when I reload the map

**Comment by chrisNom** [comment]
I mean, the page does a jquery.ajax call every minute and user expects to see reloaded data on it.
The attribute "values" has new values in every such "reload".
Instead, the user sees the new values appended on the old ones, like I mentioned previously:
Italy: 16
But, when I reload the map, the labels get a new value along with their old one:
Italy: 16: 37

**Comment by AdrienCS** [comment]
You should not re-draw all the map at every call. What about gathering data on a Event.mouseover on the country ? And then filling the overed-country's label with collected data.

Here is a shot :

```javascript
$('#vmap').vectorMap({
    ... ,
    onRegionOver: function (event, code, region)
    {
        //do things here
        $.ajax({
            url: '/country/getCount/' + code,
            success: function(response) {
                $('.jqvmap-label').text(region + ' : ' + response->count)
            }
        });
    }
});
}
```

If you are worry about performance, you can store those data in cookies for each users, or use a Cache engine.

**Comment by chrisNom** [comment]
But the user does not do mouse-over.
The map is on a dashboard page which is for monitoring some global information and it is "auto-refreshing"

**Comment by AdrienCS** [comment]
Then substring the name of the region ?

```javascript
var countryName = label.substr(0, label.indexOf(':')); // Cut 'Italy ' from 'Italy : 16, 84'
label.text(countryName + ': ' + sample_data[code]) // Erase the old string with the new one.
```

**Comment by chrisNom** [comment]
I finally managed to do it right (or at least it works for me)
Thanks Adrien for the tip of label.text()!

This is my whole solution:
```
$.ajax({
url: '@Href("~/Report/AlertsPerCountry")',
data: filter,
dataType: 'json',
type: 'POST',
success: function (data) {
    // if succesfully retrieved,
    // remove the old data from map
    $('#vmap').empty();

    // and then render map
    $('#vmap').vectorMap({
        map: 'world_en',
        backgroundColor: null,
        color: '#ffffff',
        hoverOpacity: 0.7,
        selectedColor: '#666666',
        enableZoom: true,
        showTooltip: true,
        values: data,
        scaleColors: ['#C8EEFF', '#006491'],
        normalizeFunction: 'polynomial',
        onLabelShow: function (event, label, code) {
            if (data[code] > 0) {
                // if it previously had the ': count', this is a hack to remove it, as $('#vmap').empty() does not!
                if (label.text().indexOf(':') > 0) {
                    var tmpStr = label.text();
                    var tmpIdx = tmpStr.indexOf(':');
                    label.text(tmpStr.substr(0, tmpIdx) + ': ' + data[code]);

                }
                else
                    label.append(': ' + data[code]);
            }
        }
    });
}
```

**Comment by AdrienCS** [comment]
Good job !

**TODO :** Don't redraw all the map on each call ;)

**Comment by chrisNom** [comment]
Why do you insist on that? I redraw the map for a reason.
The color density on each country shows the number of alerts on it.
I will prove you that redrawing is necessary with an example.

1: data={countyA:5, countryB:10} 
Map shows all countries white except for 2: countryA with light blue & countryB with dark blue

2: data={countyA:5, countryB:10, countryC: 40} 
After a callback, you see, a third country is fetched with a higher value the map now SHOULD redraw and update colors for the new AND the existing countries: countryA with light blue & countryB with medium-dark blue & countryC with dark blue

If I do not redraw I cannot achieve the above

**Comment by AdrienCS** [comment]
You can color anything you want on the map without redrawing ALL the map.
```javascript
jQuery('#vmap').vectorMap('set', 'colors', {country-1: '#0000ff'});
```
Or in your case : 
```javascript
jQuery('#vmap').vectorMap('set', 'scaleColors', {['#C8EEFF', '#006491']}); // Not sure for the format of the third param.
```

**Comment by chrisNom** [comment]
But then I would replace the built in functionality given by jqvmap!!
In the case of the example I gave you, I suppose that would not offer me nothing... except for ...complexity... :)
