### ISSUE TITLE
Is there a way to retrieve colors range in legend?

### ISSUE THREAD

**Issue by stporteur** [manifestinteractive/jqvmap#36]
Hi all,

I would like to know if there is a way to retrieve calculated colors and the range applied for each of them.
This is to generate a legend next to the map with the range associated to each color.

Thank you
Thierry

**Comment by cozyapps** [comment]
I'd also need to have a legend describing the colors in the map. If this feature is not planned, could you suggest some other js widgets that could be used to display a legend separately?

**Comment by githubtd01** [comment]
I also think it would be great to have a legend.
