### ISSUE TITLE
Missing Mayotte island

### ISSUE THREAD

**Issue by julienmru** [manifestinteractive/jqvmap#53]
The island of Mayotte is missing, it should be next to Comoros.

Any way to add to in the existing world map?

Here's more information: http://en.wikipedia.org/wiki/Mayotte

**Comment by LeTo34** [comment]
Hi, I have a solution. Just that you add this code in the file "jquery.vmap.france.js".
Mayotte will be placed just above "Reunion"

`"976": {"path": "M72.38,180.39l-0.52,0.0l-2.02,-6.29l2.65,-2.73l0.87,2.15l0.24,2.21l-0.38,2.26l-0.84,2.4ZM41.49,157.27l-1.04,0.75l-0.14,0.46l1.6,0.36l0.6,0.88l2.18,1.87l2.93,3.52l1.63,1.28l2.49,0.62l4.96,-0.04l2.61,0.78l2.6,1.74l1.05,1.73l0.02,2.1l-0.68,2.82l-3.71,5.46l-1.53,1.19l0.14,2.09l1.04,1.92l2.81,1.86l-0.3,1.89l-3.07,6.4l-2.6,3.07l-1.21,3.45l2.82,4.18l-1.15,1.69l-1.53,1.06l-0.76,-1.37l-0.41,-0.2l-1.1,0.17l-1.53,1.03l-1.83,0.51l-1.63,-0.43l-2.25,-1.33l-1.24,0.41l0.12,-1.88l-0.84,-1.8l-1.74,-0.77l-1.92,0.17l0.0,-0.31l2.91,-1.61l0.29,-2.68l-1.49,-2.81l-2.83,-1.57l0.22,-0.43l1.06,-0.67l1.55,-0.14l0.82,0.5l2.83,3.33l2.81,1.68l1.89,-0.73l0.6,-2.42l-0.76,-2.88l-1.37,-2.17l-1.74,-1.96l-4.21,-3.56l2.58,-0.75l0.36,-0.4l-0.07,-1.34l-0.91,-1.33l-0.68,-2.3l-0.55,-4.71l-0.6,-2.37l-1.57,-1.23l-1.87,-0.61l-1.59,-1.03l-1.74,-2.81l-0.41,-4.1l7.31,-7.87l0.59,1.27l-0.82,0.34Z", "name": "Mayotte"},`

**Comment by manifestinteractive** [comment]
@LeTo34 is there any way you can submit a Pull Request with your entire file?  If you can make a PR, I can actually get this integrated for everyone else to use.
