### ISSUE TITLE
how to link xml data to a country when its clicked

### ISSUE THREAD

**Issue by KaylanBrunet** [manifestinteractive/jqvmap#55]
I have a xml file containing information (title and Url) about some countries. when i'll click a country, i would like to show the title and the url. How can i do this? how can i link a xml file and info to the map to be able to show in the page the links for the country that is clicked/selected?

Can somebody help me? I'm stuck :/

**Comment by manifestinteractive** [comment]
Closing due to age of ticket without resolution.
