### ISSUE TITLE
Is there a way reset all countries color?

### ISSUE THREAD

**Issue by krzkrzkrz** [manifestinteractive/jqvmap#6]
Is there a way to set all country colors back to their default color? Or, is there a way to set all countries to a specific color?

I tried setting it with `color` to no avail.

**Comment by Sachem** [comment]
No need to pass the list of all regions to change their color:

$('.jqvmap-region').attr('fill', '#fff');
$('.jqvmap-region').attr('original', '#fff'');

**Comment by danielefavi** [comment]
Thanks @Sachem 
it worked!
