### ISSUE TITLE
JQVMap - Setting regions as disabled/unselectable

### ISSUE THREAD

**Issue by emagineering** [manifestinteractive/jqvmap#60]
I want to set regions in the map without data to be disabled from clicking. Is there any way to do that...I have been successful with disabling color change onRegionOver, but the same regions still responds to click (and changes color of region...). I tried calling preventDefault() method from onRegionOver and onRegionClick events...But it did not help... Would appreciate any help.

Please see: http://tinyurl.com/bqx6qjb

**Comment by manifestinteractive** [comment]
This issue has been resolved in the latest release ( v1.1.0 ).
