### ISSUE TITLE
Use of indexOf function

### ISSUE THREAD

**Issue by danielgimeno** [manifestinteractive/jqvmap#61]
I have been using this plugin with Internet Exploter, whith several problems. I have found in the code the use of indexOf, wich is not supported in this "browser" 6, 7, or 8 

http://msdn.microsoft.com/en-us/library/ie/ff679977%28v=vs.94%29.aspx

Is there any solution? 

Thank You Daniel.

**Comment by manifestinteractive** [comment]
Closing due to age of ticket and apparent resolution.
