### ISSUE TITLE
Shapefile for world map

### ISSUE THREAD

**Issue by teneightfive** [manifestinteractive/jqvmap#64]
Hi,

Does anybody have the shapefile and data used to generate the world map for this version. Basically, I need a map that includes Antarctica and can't seem to find a good combo between this version and the jvectormap version. 

The JQV world map has some countries split out a bit better and includes a few more of the smaller countries but it also doesn't contain antarctica. 

Thanks in advance.

**Comment by manifestinteractive** [comment]
Closing due to age of ticket without resolution.
