### ISSUE TITLE
Inconsistencies(packed vs. unminified)

### ISSUE THREAD

**Issue by mrjacobfisher** [manifestinteractive/jqvmap#70]
In working with this plugin, I've found that there are some differences between the minified and un-minified versions in the latest 'stable' branch.

In the packed version, the argument 'selectedRegions' does not accept multiple arguments, so only one region can be selected.

The un-minified version allows multiple regions to be selected by default, but clicking on a region removes the selected color from these regions and does not allow new regions to be selected.

![Screen Shot 2013-03-13 at 2 46 44 PM](https://f.cloud.github.com/assets/3064665/255810/c66c6400-8c16-11e2-9b20-b5ef4eaf1bfa.png)

**Comment by manifestinteractive** [comment]
This issue has been resolved in the latest release ( v1.1.0 ).
