### ISSUE TITLE
Selected Region Not working

### ISSUE THREAD

**Issue by BDatacloud** [manifestinteractive/jqvmap#75]
with the following configuration script I would expect the map to load with California to be bright green. This does not appear to be working?

selectedColor: '00ff00',
selectedRegion: 'CA',

this map can be seen at:

http://www.craftmadebrands.com/Craftmade-Locations.html

<script>
jQuery('#vmap').vectorMap({
    map: 'usa_en',
    backgroundColor: '#ffffff',
    borderColor: '#cccccc',
    borderOpacity: 0.25,
    borderWidth: 1,
    color: '#4da2b7',
    enableZoom: true,
    hoverColor: '#999999',
    hoverOpacity: null,
    normalizeFunction: 'linear',
    scaleColors: ['#b6d6ff', '#005ace'],
    selectedColor: '00ff00',
    selectedRegion: 'CA',
    showTooltip: true,
    onRegionClick: function(element, code, region)
    {	var urlLocation = '/Craftmade-Showrooms-' + 
	region.replace(' ','-','all') + '-' + code.toUpperCase() + '.html' ;
	window.location.href = urlLocation ;
    }
});
</script>

**Comment by manifestinteractive** [comment]
This issue has been resolved in the latest release ( v1.1.0 ).
