### ISSUE TITLE
Dynamic Highlight in to a state(US MAP)

### ISSUE THREAD

**Issue by v1nc3nt** [manifestinteractive/jqvmap#79]
Is there a way to dynamically highlight a state(US map)? e.g. a dropdown with list of states in us.
![untitled](https://f.cloud.github.com/assets/4547416/615919/1445cb34-ce4e-11e2-84a3-4e501b75db7f.png)

**Comment by manifestinteractive** [comment]
This is not currently supported and will require you to write custom code to be implement.
