### ISSUE TITLE
Generating map using python

### ISSUE THREAD

**Issue by AgentSource** [manifestinteractive/jqvmap#8]
Rig info:

Mac OS X 10.6.8
Python 3.2.2

Have issues creating a map, I have tried a few times in terminal and I keeps spitting back variables it doesn't like or won't run what so ever.  The fallowing snippet it the command I run to attempt to create the map.

python \
      converter.py \
      mn.shp \
      mnmap.js \
      --width 900 \
      --country_name_index 4 \
      --where "ISO = 'USA'" \
      --codes_file path/to/codes-en.tsv \
      --insets '[{"codes": ["US-AK"], "width": 200, "left": 10, "top": 370}, {"codes": ["US-HI"], "width": 100, "left": 220, "top": 400}]' \
      --minimal_area 4000000 \
      --buffer_distance -3000 \
      --simplify_tolerance 1000 \
      --longtitude0 10w \
      --name us

I apologize in advance if I'm missing something.

**Comment by cellulosa** [comment]
I'm really sorry to bother you guys, but I don't quite get how to create maps. I see there are some downloadable files on the jvectormap site, but these do not seem to work with jqvmap. Also, on the Natural Earth website there are only 3 files... Is it the case that you select what country to compile via the converter? And how to generate one map with a single state's region and then sub-maps per each reason that show the different provinces?
