### ISSUE TITLE
Clickable continents on the world map - not countries?

### ISSUE THREAD

**Issue by SBNetsolutions** [manifestinteractive/jqvmap#80]
Hi everyone,

currently I am working on a website, where I need to use a three layer navigation by clickable maps ( world ->continent->country). Is there any jquery map with all the continents on it, where the countries are not separately clickable, just the whole continent?

Thanks a lot in advance.   

Svet

**Comment by manifestinteractive** [comment]
Closing due to age of ticket without resolution.
