### ISSUE TITLE
split Sudan

### ISSUE THREAD

**Issue by taubmann** [manifestinteractive/jqvmap#82]
Sudan should now be splitted to North- and South-Sudan

**Comment by manifestinteractive** [comment]
These maps are generated by a third party application ( as mentioned in the docs ).  If they are generated incorrectly, there is nothing anyone can do about it.

**Comment by andreasspeck** [comment]
I would like to reopen this, as I also need South Sudan (and potentially Palestine).

The documentation in the Readme.md on custom maps does not include an example for rebuilding the world map (much more useful). I am also not sure the instructions match the ones for the present version of converter.py on http://jvectormap.com/documentation/gis-converter/. It is possible an older release of converter.py needs to be used, but it would be good to know which one before experimenting a lot. The mercator world map on jvectormap is 900x583, while the world map of jqvmap is 950x550 (maybe that's not a problem though). But the formats of the map files also seem to differ - maybe they were more similar in an earlier release of jvectormap (and corresponding converter.py)?

**Comment by andreasspeck** [comment]
Looking through older versions of the jvectormap website, it might be that converter.py-1.2.2 is the one, and in the website version from 2014-10-01 there might be a workable example I can extract: https://github.com/bjornd/jvectormap-site/blob/2014-10-01/content/documentation/gis-converter.html .

I'll give that a try tomorrow and report back. If that produces a workable map, I'd suggest to update the documentation of jqvmap, as it seems jvectormap (and converter.py) have moved on.

**Comment by manifestinteractive** [comment]
JQVMap does not offer a map creator / converter, which is why I closed this issue.  Our documentation says to use the other project if you wish to make custom maps.  Their maps will likely still be compatible as it's literally just JSON data of node points.

I am more than happy to add / update any maps others create, which I have done in the past.  I just want to make the distinction that JQVMap does not make maps.  These are provided by the community.

**Comment by mayeulk** [comment]
steelcrashed version does not work anymore. I updated his file here:

https://github.com/mayeulk/jqvmap/blob/master/jquery.vmap.world-update.js

Changes:
  pathes -> path
"North Sudan" -> "Sudan"
