### ISSUE TITLE
MoseOver no function at all

### ISSUE THREAD

**Issue by AceLine** [manifestinteractive/jqvmap#88]
Hallo Developer-Team!

I need help on one issue: The site you can see the problem is: http://www.yapeople.com/Hans+Spitzer/at

If you open this Link you'll see in the left column at the very bottom how I integrated the world map. It works all fine, the only problem is that MouseOver and Click-Events are not working at all... I can't see changing colors, tooltips onMouseOver, nore can I select any country onClick.

Please be so kind to give me an advice or an idea on how to solve this problem.

Best regards and thank you in advance,

Ingmar Erdös

**Comment by manifestinteractive** [comment]
Sample website did not exist.
