### ISSUE TITLE
View the id of the region

### ISSUE THREAD

**Issue by corgato** [manifestinteractive/jqvmap#91]
Hello,

I am looking for how I could display the id of a region in the center of the area if possible ... If possible I would like it automatically appears in the center, to avoid having to do it on each card ...

Thank you !

**Comment by manifestinteractive** [comment]
There now a PIN feature in v1.1.0 that might be close to what you are looking for.  You can now add a pin label, or custom image in the center of a region.  See https://github.com/manifestinteractive/jqvmap/blob/master/samples/pins.html for example.
