### ISSUE TITLE
Bahrin is not in map

### ISSUE THREAD

**Issue by cracki** [manifestinteractive/jqvmap#94]
hi
first i want to say thank you for this gr8 plugin
and then , Bahrain in not on map

how i can manually add this country?

**Comment by manifestinteractive** [comment]
These maps are generated by a third party application ( as mentioned in the docs ).  I do not create maps ( I'd have to make a LOT if I started to do that ).  If someone wants to make a custom map, and create a Pull Request for it, I will be happy to merge it.

**Comment by enghelewa** [comment]
@manifestinteractive  I'v successfully created Bahrain's map but don't know how to merge it within the world's map :( !!
