### ISSUE TITLE
borderOpacity and borderWidth Handle Zero Values Incorrectly 

### ISSUE THREAD

**Issue by Undistraction** [manifestinteractive/jqvmap#95]
Setting `borderWidth: 0` does not remove the border, however setting `borderWidth:0.01` does.

Setting `borderOpacity:0` does not hide the border, however setting `borderOpacity:0.01` does.

In both cases it looks like some kind of rounding error.

Checked in Chrome, FFox and Safari on OSX

**Comment by jenlampton** [comment]
Did you try using `null` instead of zero?  I noticed that in the examples.

**Comment by manifestinteractive** [comment]
Setting to `null` should solve this for you.  This is a bug with SVG as setting zero still technically sets a border.
