### ISSUE TITLE
OnRegionClick and event.preventDefault

### ISSUE THREAD

**Issue by LorenDorez** [manifestinteractive/jqvmap#99]
Ho I am trying to prevent the clicking of certain states but it isnt working.

After further debugging this code always returns false 

```
!regionClickEvent.isDefaultPrevented()
```
If i check this its true..
```
e.originalEvent.defaultPrevented
```

**Comment by manifestinteractive** [comment]
This issue has been resolved in the latest release ( v1.1.0 ).
